id: I0C97DB87
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T09:38:37.816348'
last_modified: '2022-06-19T09:38:37.816360'
parser: null
source_metadata:
  title: Hagiography of bKa gyur ba chen po mGon po bsod nams mchog ldan (1603–1659);
    Lamdre Lobshe, vol. nga, title no. 6
  author: ངག་དབང་བློ་བཟང་བརྒྱ་མཚོ།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2013-09-03);
    pagination incomplete (pp. 601-701), unrevised, no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:རྫོང་སར་ཁམས་བྱེའི་ལྔ་རིག་སློབ་གླིང་། སྡེ་དགེ་རྫོང་སར། (dzkj)
  - Editorial process:Mathias Fermer (mf), ཀུན་དགའ་རྡོ་རྗེ། (Kathmandu) (kun)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/572
  bases:
    4ac4:
      title: Hagiography of bKa gyur ba chen po mGon po bsod nams mchog ldan (1603–1659);
        Lamdre Lobshe, vol. nga, title no. 6
      order: 1
      base_file: 4ac4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
